name: Context Example

on: ['push']

jobs:
  my_context:
    runs-on: ubuntu-latest
    steps:
      - name: "1st step"
        runs: |
          echo "Action! $MY_ACTION"
          echo "Actor! $MY_ACTOR"
        env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}








